import type { Metadata } from "next";
import { buildMetadata } from "@/lib/seo/metadata";
import TroubleshootingArticleShell from "@/components/tools/TroubleshootingArticleShell";
import ConnectionOptimizerClient from "@/components/tools/ConnectionOptimizerClient";

export const metadata: Metadata = buildMetadata({
  title: "Router Not Assigning IP Addresses? Fix DHCP Issues (Updated 2026)",
  description:
    "Struggling with a 169.254.x.x IP address or 'No valid IP configuration' error? Fix your router's DHCP server, lease tables, and IP conflicts in minutes.",
  canonical: "/router-not-assigning-ip-addresses",
  keywords: [
    "router not assigning ip addresses",
    "no valid ip configuration",
    "169.254 ip address fix",
    "router dhcp not working",
    "ethernet self assigned ip",
    "dhcp server unavailable",
    "router not giving ip addresses",
    "automatic private ip address"
  ],
});

const breadcrumbs = [
  { name: "Router Problems", url: "/router-keeps-restarting" },
  { name: "Router Not Assigning IP Addresses", url: "/router-not-assigning-ip-addresses" },
];

const troubleshootingSteps = [
  {
    title: "Verify Client-Side IP Allocations & Subnet Range",
    description: "Inspect the network adapter's current configuration. If the IP address falls within the 169.254.0.0/16 block, your client operating system has failed to obtain an IP lease from the DHCP server and has fallen back to APIPA.",
    tip: "An APIPA address is a strong indicator of a Layer 2 or Layer 3 handshake failure between the client adapter and the DHCP daemon."
  },
  {
    title: "Force DHCP Request Cycle via OS CLI",
    description: "Release and renew the IP configuration. On Windows, use 'ipconfig /release' and 'ipconfig /renew' in an elevated shell. On macOS/Linux, toggle the network interface down and up or use the networksetup tool to force a DHCP lease renegotiation.",
    tip: "This forces the operating system to send a new DHCP Discover broadcast packet, clearing stale states."
  },
  {
    title: "Configure a Temporary Static IP Address",
    description: "Bypass the DHCP server by manually configuring a static IP in the router's subnet (e.g., IP: 192.168.1.250, Subnet Mask: 255.255.255.0, Gateway: 192.168.1.1). This will let you access the router admin console to debug.",
    tip: "Ensure you select an IP address high in the subnet range to avoid conflicts with active leases."
  },
  {
    title: "Clear DHCP Lease Tables and Re-size Pool",
    description: "Log into the router dashboard, navigate to the DHCP settings, and inspect the pool range and active leases. If the lease table is full, increase the pool size, reduce the lease time to 12-24 hours, and clear inactive bindings.",
    tip: "High-traffic networks should avoid long lease times (such as 7 days) to prevent lease pool depletion."
  },
  {
    title: "Inspect Mesh Nodes and Disable Rogue DHCP Servers",
    description: "Ensure that secondary routers, Wi-Fi extenders, or access points on your LAN are in Access Point (AP) or Bridge mode. Multiple active DHCP servers on a single subnet will conflict, causing client lease allocation failure.",
    tip: "A rogue DHCP server can assign incorrect default gateway IPs, routing local packets into dead links."
  }
];

const faqs = [
  {
    question: "Why is my router giving client devices a 169.254.x.x IP address?",
    answer: "A 169.254.x.x IP address is an Automatic Private IP Address (APIPA) generated by your device's operating system. It indicates that the physical link is active, but the device's DHCP Discover broadcast failed to receive a DHCP Offer response from the router's DHCP server."
  },
  {
    question: "Can too many devices exhaust DHCP leases on a home router?",
    answer: "Yes. By default, many routers limit their DHCP address pool range (e.g., from 192.168.1.100 to 192.168.1.149, supporting only 50 devices). If family members, guests, and smart home IoT appliances connect, the pool will exhaust. Stale leases are held until the lease time expires, blocking new devices from obtaining IPs."
  },
  {
    question: "Why does my Ethernet connection say 'No valid IP configuration'?",
    answer: "This error is displayed by Windows when the network adapter is connected to a local switch port but cannot obtain network parameters via DHCP. This happens due to a crashed DHCP service on the router, an active VPN virtual adapter conflict, or a network loop triggering Spanning Tree Protocol (STP) ports to block traffic."
  },
  {
    question: "How does a factory reset fix router DHCP server crashes?",
    answer: "A factory reset clears all corrupted databases, active lease logs, and configurations stored in the router's NVRAM/Flash memory. It restarts the DHCP server daemon (like dnsmasq) with default factory pool ranges and clears memory leaks that cause the service to crash under heavy load."
  },
  {
    question: "Can an active VPN client block DHCP IP address renewals?",
    answer: "Yes. VPN clients install virtual network adapters and modify the routing table to force all outbound traffic through the VPN tunnel. If a device attempts to renew its DHCP lease while local routing rules are intercepted, the DHCP broadcast packets may be blocked, causing the local link to time out."
  },
  {
    question: "Should I shorten the DHCP lease time on my router?",
    answer: "Yes, particularly if you have many guest devices or a high turnover of connections. Shortening the lease time from the default 24 or 72 hours to 12 hours or 8 hours forces the router to reclaim unused IP addresses faster, preventing IP lease pool exhaustion."
  }
];

const commonCauses = [
  {
    title: "APIPA Fallback Activation",
    desc: "The client operating system fails to complete the four-way DHCP handshake (DORA) within the timeout window, reverting to a local 169.254.x.x address."
  },
  {
    title: "Lease Pool Exhaustion",
    desc: "The router's allocated IP address pool has no available addresses left because stale leases from disconnected devices have not yet expired."
  },
  {
    title: "Rogue DHCP Server Conflict",
    desc: "A secondary wireless extender, access point, or router has its DHCP server active on the same subnet, causing conflicting address offers."
  },
  {
    title: "Router RAM Memory Leak",
    desc: "The router's lightweight DHCP server daemon (e.g., dnsmasq) runs out of operating RAM buffers due to packet overload, causing the service to crash."
  }
];

export default function RouterNotAssigningIpAddressesPage() {
  return (
    <TroubleshootingArticleShell
      h1="Router Not Assigning IP Addresses? Fix DHCP Issues Fast"
      intro="If your computer is showing a 169.254.x.x IP address, experiencing an APIPA fallback loop, or throwing a 'No valid IP configuration' network diagnostic result, your client device has failed to receive network routing parameters. Follow our step-by-step diagnostic guide to troubleshoot router DHCP service crashes, clear full lease tables, configure manual IP parameters, and restore local network access in minutes."
      category="wifi"
      breadcrumbs={breadcrumbs}
      faqs={faqs}
      troubleshootingSteps={troubleshootingSteps}
      warningBanner={{
        title: "Dynamic Allocation Failure Warning",
        text: "When modifying your router's DHCP lease pool size or lease times, do not disable the DHCP server daemon entirely unless you have configured a static IP on your management client. Disabling DHCP without a manual IP binding will lock you out of the router administration interface."
      }}
      quickFixChecklist={[
        "Run 'ipconfig /release' and 'ipconfig /renew' in an elevated terminal.",
        "Verify your device is not assigned a self-signed APIPA IP address (169.254.x.x).",
        "Clear the router's active DHCP lease tables and increase the IP address pool range.",
        "Disable secondary DHCP servers on access points, range extenders, or mesh nodes.",
        "Perform a sequential power cycle of your modem, router, and client devices."
      ]}
      commonCauses={commonCauses}
      whenToContactISP="If client devices continue to receive APIPA addresses after performing a factory reset and connecting directly to the router's physical LAN ports, the DHCP controller integrated circuit on the router board may have suffered a chip-level failure. Contact your ISP to replace the residential gateway."
      severityLevel="high"
    >
      <div className="space-y-6">
        {/* Quick Answer Snippet for AI Search Engines */}
        <section className="glass-card p-5 border border-amber-950/20 bg-amber-950/5 rounded-2xl relative overflow-hidden" aria-label="Quick Answer Summary">
          <div className="absolute top-0 right-0 bg-amber-500/10 text-amber-400 text-[10px] font-mono uppercase tracking-wider px-2 py-0.5 rounded-bl-lg font-bold">
            AIO Quick Answer
          </div>
          <h3 className="text-xs font-bold text-amber-400 mb-2 uppercase tracking-wide">Quick Diagnostic Summary</h3>
          <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
            A router failing to assign local IP addresses indicates a breakdown in the **DHCP DORA handshake** (Discover, Offer, Request, Acknowledge). This is usually caused by **lease pool exhaustion** (too many smart devices using stale leases), **STP blocking** due to a local network loop, or **VPN software conflicts**. Resolve this immediately by renewing your lease manually or configuring a static IP address in your router's subnet range to bypass DHCP.
          </p>
        </section>

        <ConnectionOptimizerClient mode="ethernet-no-internet" />

        <article className="prose prose-invert max-w-none space-y-6 text-xs md:text-sm text-[var(--text-secondary)] leading-relaxed">
          
          <h2 className="text-sm font-bold text-[var(--text-primary)]">What is the DHCP DORA Handshake?</h2>
          <p>
            The Dynamic Host Configuration Protocol (DHCP) operates at the Application Layer of the TCP/IP suite. It dynamically delegates IP parameters to local devices, avoiding manual configurations. This lease allocation process follows a four-step handshake, often referred to as **DORA**:
          </p>
          <ul className="list-disc pl-5 space-y-3 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>Discover (Client to Broadcast):</strong> When a client device connects to the network (physical cable insertion or Wi-Fi association), it does not have an IP. It broadcasts a <code>DHCPDISCOVER</code> packet containing its hardware MAC address over UDP port 68 to destination 255.255.255.255.
            </li>
            <li>
              <strong>Offer (Router to Client):</strong> The router's DHCP daemon (listening on UDP port 67) receives the broadcast. It checks its active lease tables, reserves an available IP, and unicasts or broadcasts a <code>DHCPOFFER</code> packet containing the proposed IP, subnet mask, default gateway, DNS servers, and lease duration.
            </li>
            <li>
              <strong>Request (Client to Router):</strong> The client receives the offer. If multiple offers are received (due to rogue routers), it selects one and broadcasts a <code>DHCPREQUEST</code> packet, letting all servers know it has accepted the specific offer.
            </li>
            <li>
              <strong>Acknowledge (Router to Client):</strong> The chosen router receives the request, binds the client's MAC address to the leased IP, and returns a <code>DHCPACK</code> packet to confirm the lease is active.
            </li>
          </ul>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Why Do Devices Fall Back to a 169.254.x.x APIPA IP?</h2>
          <p>
            If a client device broadcasts a <code>DHCPDISCOVER</code> packet but receives no reply within its timeout window, the operating system invokes **APIPA** (Automatic Private IP Addressing). APIPA is a fallback protocol defined by RFC 3927 that assigns a temporary link-local IP in the range **169.254.1.0 to 169.254.254.255** with subnet mask **255.255.0.0**.
          </p>
          <p>
            An APIPA IP allows you to communicate with other local devices that also failed to obtain an IP. However, because APIPA has no default gateway parameter, devices cannot route packets beyond their immediate local link. The appearance of a 169.254.x.x IP address is confirmation that the DORA handshake failed, typically due to a crashed router DHCP service or signal attenuation.
          </p>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Step-by-Step Settings Optimization by Brand</h2>
          <p>
            If you need to verify or configure your router's DHCP server settings, follow these instructions for the major residential router brands:
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)] uppercase">1. TP-Link (Tether App / Web UI)</h3>
          <p>
            Log into the web dashboard (192.168.0.1 or tplinkwifi.net). Go to **Advanced** &rarr; **Network** &rarr; **DHCP Server**. Verify that the DHCP Server checkbox is selected. Check the IP Address Pool range (ensure it supports enough devices, e.g. 100 to 249). Set the Address Lease Time to 120 minutes (for high turnover networks) or 1440 minutes (default 24 hours).
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)] uppercase">2. ASUS (ASUSWRT console)</h3>
          <p>
            Go to **Advanced Settings** &rarr; **LAN** &rarr; **DHCP Server** tab. Enable the DHCP Server toggle. You can set the IP pool range and configure **Manual Assignment** (MAC binding) at the bottom of the page.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)] uppercase">3. Netgear (Nighthawk / Orbi)</h3>
          <p>
            Go to **Advanced** &rarr; **Setup** &rarr; **LAN Setup**. Ensure the **Use Router as DHCP Server** checkbox is selected. You can set the start and end IP addresses and configure static address reservations here.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)] uppercase">4. Linksys</h3>
          <p>
            Go to **Connectivity** &rarr; **Local Network** &rarr; **DHCP Server**. Toggle the DHCP Server to Enabled, adjust the client lease time, and save your changes.
          </p>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Hardware Failures Causing DHCP Drops</h2>
          <p>
            If a router continues to drop DHCP allocations even after a factory reset and with minimal devices connected, the hardware itself may be failing:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>RAM Degradation:</strong> The DHCP lease table is maintained in the router&apos;s system RAM. If the RAM chips degrade due to voltage fluctuations or age, data writes to the lease tables can fail, causing the DHCP service to crash.
            </li>
            <li>
              <strong>Thermal Throttling of the Switch SoC:</strong> Many home routers are fanless and rely on small passive heatsinks. If the router is placed in an unventilated area, the switch chip can overheat. This causes the router to drop packets and fail to process DHCP broadcasts, even while maintaining active LED link lights.
            </li>
            <li>
              <strong>Physical Port and PHY Chip Faults:</strong> Power surges can damage the physical Ethernet PHY transceiver chips behind the LAN ports. This damage can prevent client handshake frames from reaching the CPU, preventing the DHCP server from receiving the Discover request.
            </li>
            <li>
              <strong>Capacitor Aging:</strong> Swollen or failing electrolytic capacitors on the router&apos;s mainboard can cause voltage instability, leading to random CPU resets and crashes of network daemons like the DHCP service.
            </li>
          </ul>

          <div className="p-4 border border-[var(--border-subtle)] bg-[var(--bg-elevated)] rounded-xl space-y-2">
            <span className="font-bold text-[var(--text-primary)] block text-xs">Deep Diagnostics & Internal Authority Links</span>
            <ul className="list-disc pl-4 space-y-1 text-[11px]">
              <li>If you need step-by-step guidance on updating router interfaces, read our <a href="/how-to-change-dns-on-router" className="text-[var(--brand-400)] hover:underline">How to Change DNS on Router Walkthrough</a>.</li>
              <li>Learn how to optimize routing targets with our <a href="/dns-server-not-responding" className="text-[var(--brand-400)] hover:underline">DNS Server Not Responding Diagnostics</a>.</li>
              <li>Verify your gateway configuration endpoints at the <a href="/ips/192-168-1-1" className="text-[var(--brand-400)] hover:underline">192.168.1.1 Gateway Portal</a>.</li>
              <li>Analyze your wireless dropouts using the <a href="/wifi-keeps-disconnecting" className="text-[var(--brand-400)] hover:underline">WiFi Disconnection Walkthrough</a>.</li>
              <li>Check your physical link speed using the <a href="/ethernet-connected-but-no-internet" className="text-[var(--brand-400)] hover:underline">Ethernet Connected but No Internet Optimizer</a>.</li>
              <li>Isolate packet drop bottlenecks using the <a href="/packet-loss-test" className="text-[var(--brand-400)] hover:underline">Packet Loss Test Tool</a>.</li>
              <li>Learn how nested routers create address translation issues at the <a href="/double-nat-detected" className="text-[var(--brand-400)] hover:underline">Double NAT Diagnostic</a>.</li>
              <li>Optimize console gaming settings with the <a href="/best-dns-for-ps5" className="text-[var(--brand-400)] hover:underline">Best DNS for PS5 Guide</a>.</li>
              <li>Verify gateway IP options at the <a href="/default-gateway-not-available" className="text-[var(--brand-400)] hover:underline">Default Gateway Unreachable Guide</a>.</li>
              <li>Instantly identify hardware brands using our <a href="/mac-address-lookup" className="text-[var(--brand-400)] hover:underline">MAC Address Lookup Tool</a>.</li>
            </ul>
          </div>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">How ISPs Detect DHCP Issues Remotely</h2>
          <p>
            Internet Service Providers monitor network equipment performance up to your home gateway using several telemetry tools:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>CMTS Loop Diagnostic Logging:</strong> On cable networks, the **Cable Modem Termination System (CMTS)** monitors downstream DOCSIS channels. If a client router generates broadcast storms (e.g., from an STP network loop), the CMTS logs an alert and may throttle the connection to protect the node.
            </li>
            <li>
              <strong>DHCP IP Lease Expiry Telemetry:</strong> ISP routers check RADIUS and DHCP server logs for lease request patterns. If your router stops sending DHCP Request packets before its WAN lease expires, the ISP systems will log a provisioning timeout and mark the connection as offline.
            </li>
            <li>
              <strong>Modem SNMP Poll Errors:</strong> ISPs use Simple Network Management Protocol (SNMP) to poll modems and ONT units. If the ONT reports high packet drop rates on its Ethernet port, it indicates a link negotiation issue between the modem and your primary router.
            </li>
          </ul>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">When to Replace Your Router</h2>
          <p>
            Troubleshooting can only resolve configuration errors. If your router displays the following symptoms, it is time to replace the hardware:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>Recurring DHCP Crashes:</strong> The router stops assigning IP addresses every 24 to 48 hours, requiring a physical power cycle to restore network connectivity.
            </li>
            <li>
              <strong>NVRAM Write Errors:</strong> Settings changes, static IP reservations, or custom DNS configurations revert to default values after the router is rebooted.
            </li>
            <li>
              <strong>High Thermal Output:</strong> The router chassis feels hot to the touch, and throughput speeds drop under heavy network load.
            </li>
          </ul>
        </article>
      </div>
    </TroubleshootingArticleShell>
  );
}
