import type { Metadata } from "next";
import { buildMetadata } from "@/lib/seo/metadata";
import TroubleshootingArticleShell from "@/components/tools/TroubleshootingArticleShell";
import ConnectionOptimizerClient from "@/components/tools/ConnectionOptimizerClient";

export const metadata: Metadata = buildMetadata({
  title: "Router Not Assigning IP Addresses? Fix DHCP Issues Fast",
  description:
    "Is your device showing a 169.254.x.x IP address or 'No valid IP configuration'? Learn how to resolve DHCP server timeouts, lease pool exhaustion, and local IP conflicts.",
  canonical: "/router-not-assigning-ip-addresses",
  keywords: [
    "router not assigning ip addresses",
    "no valid ip configuration",
    "169.254 ip address fix",
    "router dhcp not working",
    "ethernet self assigned ip",
    "dhcp server unavailable",
    "router not giving ip addresses",
    "automatic private ip address"
  ],
});

const breadcrumbs = [
  { name: "Router Problems", url: "/router-keeps-restarting" },
  { name: "Router Not Assigning IP Addresses", url: "/router-not-assigning-ip-addresses" },
];

const troubleshootingSteps = [
  {
    title: "Verify Client-Side IP Allocations & Subnet Range",
    description: "Inspect the network adapter's current configuration. If the IP address falls within the 169.254.0.0/16 block, your client operating system has failed to obtain an IP lease from the DHCP server and has fallen back to APIPA.",
    tip: "An APIPA address is a strong indicator of a Layer 2 or Layer 3 handshake failure between the client adapter and the DHCP daemon."
  },
  {
    title: "Force DHCP Request Cycle via OS CLI",
    description: "Release and renew the IP configuration. On Windows, use 'ipconfig /release' and 'ipconfig /renew' in an elevated shell. On macOS/Linux, toggle the network interface down and up or use the networksetup tool to force a DHCP lease renegotiation.",
    tip: "This forces the operating system to send a new DHCP Discover broadcast packet, clearing stale states."
  },
  {
    title: "Configure a Temporary Static IP Address",
    description: "Bypass the DHCP server by manually configuring a static IP in the router's subnet (e.g., IP: 192.168.1.250, Subnet Mask: 255.255.255.0, Gateway: 192.168.1.1). This will let you access the router admin console to debug.",
    tip: "Ensure you select an IP address high in the subnet range to avoid conflicts with active leases."
  },
  {
    title: "Clear DHCP Lease Tables and Re-size Pool",
    description: "Log into the router dashboard, navigate to the DHCP settings, and inspect the pool range and active leases. If the lease table is full, increase the pool size, reduce the lease time to 12-24 hours, and clear inactive bindings.",
    tip: "High-traffic networks should avoid long lease times (such as 7 days) to prevent lease pool depletion."
  },
  {
    title: "Inspect Mesh Nodes and Disable Rogue DHCP Servers",
    description: "Ensure that secondary routers, Wi-Fi extenders, or access points on your LAN are in Access Point (AP) or Bridge mode. Multiple active DHCP servers on a single subnet will conflict, causing client lease allocation failure.",
    tip: "A rogue DHCP server can assign incorrect default gateway IPs, routing local packets into dead links."
  }
];

const faqs = [
  {
    question: "Why is my router giving client devices a 169.254.x.x IP address?",
    answer: "A 169.254.x.x IP address is an Automatic Private IP Address (APIPA) generated by your device's operating system. It indicates that the physical link is active, but the device's DHCP Discover broadcast failed to receive a DHCP Offer response from the router's DHCP server."
  },
  {
    question: "Can too many devices exhaust DHCP leases on a home router?",
    answer: "Yes. By default, many routers limit their DHCP address pool range (e.g., from 192.168.1.100 to 192.168.1.149, supporting only 50 devices). If family members, guests, and smart home IoT appliances connect, the pool will exhaust. Stale leases are held until the lease time expires, blocking new devices from obtaining IPs."
  },
  {
    question: "Why does my Ethernet connection say 'No valid IP configuration'?",
    answer: "This error is displayed by Windows when the network adapter is connected to a local switch port but cannot obtain network parameters via DHCP. This happens due to a crashed DHCP service on the router, an active VPN virtual adapter conflict, or a network loop triggering Spanning Tree Protocol (STP) ports to block traffic."
  },
  {
    question: "How does a factory reset fix router DHCP server crashes?",
    answer: "A factory reset clears all corrupted databases, active lease logs, and configurations stored in the router's NVRAM/Flash memory. It restarts the DHCP server daemon (like dnsmasq) with default factory pool ranges and clears memory leaks that cause the service to crash under heavy load."
  },
  {
    question: "Can an active VPN client block DHCP IP address renewals?",
    answer: "Yes. VPN clients install virtual network adapters and modify the routing table to force all outbound traffic through the VPN tunnel. If a device attempts to renew its DHCP lease while local routing rules are intercepted, the DHCP broadcast packets may be blocked, causing the local link to time out."
  },
  {
    question: "Should I shorten the DHCP lease time on my router?",
    answer: "Yes, particularly if you have many guest devices or a high turnover of connections. Shortening the lease time from the default 24 or 72 hours to 12 hours or 8 hours forces the router to reclaim unused IP addresses faster, preventing IP lease pool exhaustion."
  }
];

const commonCauses = [
  {
    title: "APIPA Fallback Activation",
    desc: "The client operating system fails to complete the four-way DHCP handshake (DORA) within the timeout window, reverting to a local 169.254.x.x address."
  },
  {
    title: "Lease Pool Exhaustion",
    desc: "The router's allocated IP address pool has no available addresses left because stale leases from disconnected devices have not yet expired."
  },
  {
    title: "Rogue DHCP Server Conflict",
    desc: "A secondary wireless extender, access point, or router has its DHCP server active on the same subnet, causing conflicting address offers."
  },
  {
    title: "Router RAM Memory Leak",
    desc: "The router's lightweight DHCP server daemon (e.g., dnsmasq) runs out of operating RAM buffers due to packet overload, causing the service to crash."
  }
];

const quickFixChecklist = [
  "Verify if your device IP address is in the 169.254.x.x range.",
  "Run 'ipconfig /release' and 'ipconfig /renew' in an administrator Command Prompt.",
  "Configure a manual static IP to bypass DHCP and log into the router gateway.",
  "Ensure all secondary access points or extenders are set to Bridge or AP mode.",
  "Shorten DHCP lease times in the router dashboard to free up inactive IP addresses."
];

export default function RouterNotAssigningIpPage() {
  return (
    <TroubleshootingArticleShell
      h1="Router Not Assigning IP Addresses? Fix DHCP Issues Fast"
      intro="If your computer displays a 169.254.x.x IP address, an 'Ethernet has a self-assigned IP' warning, or a 'No valid IP configuration' error, your device's DHCP handshake is failing. Learn how to debug local DHCP service crashes, release stalled lease allocations, and stabilize subnet address distribution."
      category="dns"
      breadcrumbs={breadcrumbs}
      faqs={faqs}
      troubleshootingSteps={troubleshootingSteps}
      warningBanner={{
        title: "Rogue DHCP Server Warning",
        text: "Connecting a secondary router, wireless extender, or smart plug with its DHCP server active onto your LAN creates a conflicting DHCP environment. Clients may receive incorrect gateway details, blocking all internet and local routing."
      }}
      quickFixChecklist={quickFixChecklist}
      commonCauses={commonCauses}
      whenToContactISP="If your gateway is configured in bridge mode and your local devices fail to secure WAN IP handshakes from the ISP's upstream node, or if the ISP-provided modem continues to drop its DHCP allocation tables, the ISP provisioning profile may be locking out new MAC addresses. Contact your ISP support to request a dynamic MAC binding flush on their CMTS or OLT."
      severityLevel="medium"
    >
      <div className="space-y-6">
        {/* Quick Answer Snippet for AI Search Engines */}
        <section className="glass-card p-5 border border-amber-950/20 bg-amber-950/5 rounded-2xl relative overflow-hidden" aria-label="Quick Answer Summary">
          <div className="absolute top-0 right-0 bg-amber-500/10 text-amber-400 text-[10px] font-mono uppercase tracking-wider px-2 py-0.5 rounded-bl-lg font-bold">
            AIO Quick Answer
          </div>
          <h3 className="text-xs font-bold text-amber-400 mb-2 uppercase tracking-wide">Quick Diagnostic Summary</h3>
          <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
            Routers stop assigning IP addresses when their internal <strong>DHCP server daemon crashes</strong> due to memory limits, or when the <strong>IP lease pool is exhausted</strong>. The fastest fix is to run <code className="font-mono text-amber-300">ipconfig /release</code> and <code className="font-mono text-amber-300">ipconfig /renew</code> in your terminal. If the problem persists, assign a manual static IP to access the router dashboard, expand the DHCP pool, and shorten the lease time configuration.
          </p>
        </section>

        {/* Interactive Troubleshooting Wizard */}
        <ConnectionOptimizerClient mode="ethernet-no-internet" />

        {/* Technical Article Body */}
        <article className="prose prose-invert max-w-none space-y-6 text-xs md:text-sm text-[var(--text-secondary)] leading-relaxed">
          
          <h2 className="text-sm font-bold text-[var(--text-primary)]">Symptoms vs. Root Causes Diagnostic Table</h2>
          <p>
            When Layer 2 connectivity is established but Layer 3 IP configuration fails, client systems present specific system alerts. Use the diagnostic matrix below to map errors to their corresponding fixes:
          </p>

          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-[var(--border-subtle)] text-[11px] text-[var(--text-secondary)]">
              <thead>
                <tr className="bg-[var(--bg-elevated)] text-[var(--text-primary)] font-bold">
                  <th className="px-3 py-2 text-left">Observed Symptom</th>
                  <th className="px-3 py-2 text-left">Likely Network / Protocol Fault</th>
                  <th className="px-3 py-2 text-left">Severity</th>
                  <th className="px-3 py-2 text-left">Fastest Fix</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[var(--border-subtle)]">
                <tr>
                  <td className="px-3 py-2 font-mono text-amber-400">169.254.x.x IP address</td>
                  <td className="px-3 py-2">APIPA fallback triggered; DHCP Discover queries timed out without a router reply.</td>
                  <td className="px-3 py-2">Medium</td>
                  <td className="px-3 py-2">Restart router DHCP service; check client-side network adapter configurations.</td>
                </tr>
                <tr>
                  <td className="px-3 py-2 font-mono text-amber-400">&ldquo;No valid IP configuration&rdquo;</td>
                  <td className="px-3 py-2">The network adapter failed to bind an IP within the local subnet scope.</td>
                  <td className="px-3 py-2">Medium</td>
                  <td className="px-3 py-2">Flush DNS cache and reset winsock stack; run ipconfig lease renewal.</td>
                </tr>
                <tr>
                  <td className="px-3 py-2 font-mono text-amber-400">Ethernet connected but no IP</td>
                  <td className="px-3 py-2">Physical link negotiation (Layer 1/2) is active, but the DHCP daemon is unresponsive.</td>
                  <td className="px-3 py-2">High</td>
                  <td className="px-3 py-2">Temporarily configure a manual static IP to access the router gateway.</td>
                </tr>
                <tr>
                  <td className="px-3 py-2 font-mono text-amber-400">Limited connectivity status</td>
                  <td className="px-3 py-2">IP assigned, but default gateway or DNS parameters are missing from the DHCP scope.</td>
                  <td className="px-3 py-2">Medium</td>
                  <td className="px-3 py-2">Check DHCP Option 3 (Gateway) and Option 6 (DNS) settings in router admin.</td>
                </tr>
                <tr>
                  <td className="px-3 py-2 font-mono text-amber-400">DHCP Timeout Logs</td>
                  <td className="px-3 py-2">The client's UDP port 68 handshake packets are ignored by the router due to pool exhaustion.</td>
                  <td className="px-3 py-2">High</td>
                  <td className="px-3 py-2">Expand the DHCP pool start/end range; reduce lease duration to 8-12 hours.</td>
                </tr>
                <tr>
                  <td className="px-3 py-2 font-mono text-amber-400">Self-assigned IP warning (macOS)</td>
                  <td className="px-3 py-2">The system self-allocated an IP because the local gateway DHCP interface is down.</td>
                  <td className="px-3 py-2">Medium</td>
                  <td className="px-3 py-2">Renew DHCP lease via System Settings or flush active interface bindings.</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">What Is Happening Internally? The DHCP Handshake (DORA) and APIPA Fallback</h2>
          <p>
            To understand why a router stops assigning IP addresses, it is necessary to examine the underlying Layer 7 protocol transaction: the **DHCP DORA** handshake. This transaction operates over **UDP Ports 67** (server listening port) and **UDP Port 68** (client listening port):
          </p>

          <ol className="list-decimal pl-5 space-y-2 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>Discover:</strong> The client broadcasts a DHCP Discover packet to the MAC address <code className="font-mono">FF:FF:FF:FF:FF:FF</code> and IP address <code className="font-mono">255.255.255.255</code>. This packet alerts any active DHCP server on the physical LAN segment that a client needs an IP address.
            </li>
            <li>
              <strong>Offer:</strong> The router's DHCP daemon (such as <code className="font-mono">dnsmasq</code> or <code className="font-mono">dhcpd</code>) receives the broadcast, checks its lease database, reserves an available IP, and unicasts or broadcasts a DHCP Offer containing the proposed IP, subnet mask, default gateway, and DNS servers.
            </li>
            <li>
              <strong>Request:</strong> The client receives the offer and responds with a DHCP Request broadcast, confirming it accepts the offered IP. Broadcasting this packet notifies other potential DHCP servers on the subnet that their offers have been rejected.
            </li>
            <li>
              <strong>ACK (Acknowledgment):</strong> The router receives the request, writes the client&apos;s hardware MAC address and lease timestamps to its active lease table, and sends a DHCP ACK packet to finalize the lease.
            </li>
          </ol>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">APIPA Fallback Mechanics</h3>
          <p>
            If the client system broadcasts a <strong>DHCP Discover</strong> packet but receives no valid <strong>DHCP Offer</strong> within a specific timeout window (typically 10 to 15 seconds), the operating system triggers its fallback routine: **APIPA (Automatic Private IP Addressing)**. 
          </p>
          <p>
            The OS automatically selects an address from the Link-Local block **169.254.1.0 to 169.254.254.255** (defined by RFC 3927). It then broadcasts local **ARP (Address Resolution Protocol)** queries to ensure no other device on the link is using that self-assigned IP. While this allows basic peer-to-peer communication on the local layer 2 segment, APIPA addresses do not have a default gateway. As a result, the device cannot route packets outside its local LAN segment, resulting in a loss of internet access.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">Lease Pool Exhaustion and NAT Constraints</h3>
          <p>
            Every DHCP lease has a set **lease time**. If the router&apos;s configured address range (for example, <code className="font-mono">192.168.1.100</code> to <code className="font-mono">192.168.1.150</code>) contains 50 IP addresses, and 50 unique MAC addresses have connected within the lease period, the pool is fully exhausted. 
          </p>
          <p>
            When device number 51 requests an IP, the router&apos;s DHCP daemon has no available addresses to assign, and ignores the DHCP Discover packet. Because Network Address Translation (NAT) maps internal private IP addresses to a single public WAN IP, any device without a valid local IP address lease cannot be added to the NAT translation tables, blocking internet access.
          </p>

          <div className="p-4 border border-[var(--border-subtle)] bg-[var(--bg-elevated)] rounded-xl space-y-2">
            <span className="font-bold text-[var(--text-primary)] block text-xs">Deep Diagnostics & Internal Authority Links</span>
            <ul className="list-disc pl-4 space-y-1 text-[11px]">
              <li>If you can&apos;t access the router config page to check DHCP pools, see our <a href="/router-login-not-working" className="text-[var(--brand-400)] hover:underline">192.168.1.1 Timeout Resolution Guide</a>.</li>
              <li>Learn how IP routing speeds are affected by physical links in our <a href="/ethernet-slower-than-wifi" className="text-[var(--brand-400)] hover:underline">Ethernet vs Wi-Fi Speed Analysis</a>.</li>
              <li>For DNS optimization once your IP is assigned, check out our <a href="/best-dns-for-faster-internet" className="text-[var(--brand-400)] hover:underline">Fast DNS Configuration Walkthrough</a>.</li>
              <li>Troubleshoot downstream synchronization drops with our <a href="/modem-online-light-blinking" className="text-[var(--brand-400)] hover:underline">Modem Online Light Blinking Guide</a>.</li>
              <li>If your phone gets an IP but still shows no internet connection, read our <a href="/wifi-connected-but-no-internet-phone" className="text-[var(--brand-400)] hover:underline">Mobile Wi-Fi No Internet Fix</a>.</li>
            </ul>
          </div>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Advanced Root Causes of DHCP Failures</h2>
          <p>
            Aside from simple pool exhaustion, several advanced network configurations can disrupt DHCP operations:
          </p>

          <ul className="list-disc pl-5 space-y-3 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>Disabled DHCP Server Daemon:</strong> When a router is converted to an Access Point (AP) or configured behind a primary gateway, its internal DHCP server must be disabled to avoid conflict. If this is done accidentally on a primary router, clients will fail to obtain IPs.
            </li>
            <li>
              <strong>Rogue DHCP Servers:</strong> If a secondary access point, network bridge, or virtualization server (running hypervisors like Proxmox or Hyper-V) is misconfigured to run its own DHCP server on the same VLAN, it will reply to DHCP Discover broadcasts. Devices receiving these rogue offers may be assigned invalid subnets or gateway routes.
            </li>
            <li>
              <strong>Firmware RAM Memory Leaks:</strong> Budget routers with limited RAM (e.g., 128MB or 256MB) can experience memory leaks in their DHCP daemons over time. This causes the daemon to crash, preventing it from responding to queries even though the physical Wi-Fi and Ethernet ports remain active.
            </li>
            <li>
              <strong>Mesh Topology STP Loops:</strong> In mesh Wi-Fi setups, connecting multiple mesh nodes via physical Ethernet cables without configuring Spanning Tree Protocol (STP) on the backhaul switch can trigger a **network loop**. This floods the network with broadcast packets, causing the router&apos;s CPU to spike to 100% and drop DHCP traffic.
            </li>
            <li>
              <strong>VLAN Isolation Blocks:</strong> If your network uses Virtual Local Area Networks (VLANs) to segment traffic, and your DHCP server is on a different VLAN than the client, the DHCP broadcast packets cannot cross the VLAN boundary. You must configure a **DHCP Helper Address** (IP Helper / DHCP Relay) on the Layer 3 switch or router interface to forward the broadcast packets to the DHCP server.
            </li>
            <li>
              <strong>MAC Filtering Policies:</strong> If MAC address filtering is active on the router, the DHCP daemon will ignore requests from unauthorized hardware, forcing client systems into APIPA configurations.
            </li>
            <li>
              <strong>ISP Bridge Mode Subnet Mismatches:</strong> If your primary router is connected to an ISP gateway that has not been placed in Bridge Mode, both devices may attempt to host the same subnet (e.g., 192.168.1.0/24), creating routing conflicts and blocking IP assignment.
            </li>
          </ul>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Windows 11 Console Diagnostics</h2>
          <p>
            To troubleshoot DHCP failures on Windows 11, open PowerShell or Command Prompt as an Administrator and execute the following commands. These commands interact directly with the Windows TCP/IP stack:
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">1. Release Current Address Bindings</h3>
          <pre className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-lg font-mono text-[10px] text-green-400">
            ipconfig /release
          </pre>
          <p className="text-[11px] text-[var(--text-muted)]">
            <strong>Internal Action:</strong> Instructs the DHCP client service to send a unicast DHCP Release packet (via UDP port 67) to the active DHCP gateway. This relinquishes the current IP address lease and updates the system registry.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">2. Request New IP Allocation</h3>
          <pre className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-lg font-mono text-[10px] text-green-400">
            ipconfig /renew
          </pre>
          <p className="text-[11px] text-[var(--text-muted)]">
            <strong>Internal Action:</strong> Forces the network adapter to broadcast a DHCP Discover packet. It resets the lease negotiation sequence to secure new IP address bindings and subnet routing information from the active gateway.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">3. Flush DNS Resolver Database</h3>
          <pre className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-lg font-mono text-[10px] text-green-400">
            ipconfig /flushdns
          </pre>
          <p className="text-[11px] text-[var(--text-muted)]">
            <strong>Internal Action:</strong> Purges the local DNS resolver cache, forcing the operating system to perform new DNS queries instead of relying on outdated cache data.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">4. Reset TCP/IP Stack Configuration</h3>
          <pre className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-lg font-mono text-[10px] text-green-400">
            netsh int ip reset
          </pre>
          <p className="text-[11px] text-[var(--text-muted)]">
            <strong>Internal Action:</strong> Rewrites critical TCP/IP system registry keys to their default states. This clears custom configurations, incorrect static routes, and registry corruption affecting the network stack.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">5. Reset Winsock API Catalog</h3>
          <pre className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-lg font-mono text-[10px] text-green-400">
            netsh winsock reset
          </pre>
          <p className="text-[11px] text-[var(--text-muted)]">
            <strong>Internal Action:</strong> Resets the Windows Sockets API catalog. This removes third-party LSP (Layered Service Provider) drivers and network filters installed by VPNs or security software that can intercept and block socket queries.
          </p>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">macOS / Linux Terminal Diagnostics</h2>
          <p>
            On Unix-based operating systems, network configuration is managed via configuration daemons or directly via commands. Execute these commands in Terminal:
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">Renew DHCP Leases via networksetup (macOS)</h3>
          <p>
            Identify your active network interface (typically <code className="font-mono">Wi-Fi</code> or <code className="font-mono">USB 10/100/1000 LAN</code>) and trigger a lease renewal:
          </p>
          <pre className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-lg font-mono text-[10px] text-green-400">
            sudo ipconfig set en0 DHCP
          </pre>
          <p className="text-[11px] text-[var(--text-muted)]">
            <strong>Internal Action:</strong> Resets the DHCP state machine for interface <code className="font-mono">en0</code>. This releases the current IP address and broadcasts a new DHCP Discover query.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">Release and Renew on Linux (dhclient)</h3>
          <p>
            Linux distributions utilize the ISC DHCP client daemon to manage leases. Release the current address and request a new one:
          </p>
          <pre className="p-3 bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-lg font-mono text-[10px] text-green-400">
            sudo dhclient -r eth0{"\n"}
            sudo dhclient eth0
          </pre>
          <p className="text-[11px] text-[var(--text-muted)]">
            The <code className="font-mono">-r</code> flag instructs the daemon to release the current lease on interface <code className="font-mono">eth0</code>. The second command starts a new DHCP transaction to obtain a fresh IP configuration.
          </p>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Mobile OS Configurations: Android and iOS</h2>
          <p>
            Modern mobile operating systems include security features that can complicate DHCP addressing:
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">MAC Address Randomization (Private Wi-Fi Address)</h3>
          <p>
            By default, iOS and Android randomize their MAC addresses for each SSID to prevent tracking. While beneficial for privacy, this can cause issues on local networks:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>Lease Pool Depletion:</strong> If a device frequently changes its MAC address, the router will treat it as a new device each time, assigning it a new IP address. This can quickly exhaust the DHCP lease pool.
            </li>
            <li>
              <strong>Static IP Binding Failures:</strong> MAC-to-IP binding configurations will fail if the client device uses a randomized MAC instead of its hardware MAC.
            </li>
            <li>
              <strong>Resolution:</strong> Go to the Wi-Fi settings on your mobile device, select the network name, and toggle **Private Wi-Fi Address** (iOS) or **Use Device MAC** (Android) to disable randomization for that network.
            </li>
          </ul>

          <h3 className="text-xs font-bold text-[var(--text-primary)]">Forget and Reconnect Network Profile</h3>
          <p>
            Forgetting the network profile clears cached IP configurations, lease details, and custom DNS settings stored on the device. Reconnecting forces the device to request a new IP address lease.
          </p>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Console Settings: PS5 and Xbox</h2>
          <p>
            Gaming consoles require stable, uninterrupted network paths to support multiplayer matching:
          </p>
          
          <ul className="list-disc pl-5 space-y-3 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>PS5 NAT Type Failures:</strong> A Strict NAT Type on PlayStation consoles often stems from local IP address lease changes. If the router assigns a new IP address to the console via DHCP, any port forwarding rules configured for the console&apos;s previous IP will no longer apply. To prevent this, configure an **Address Reservation** on the router to lock the console to a specific IP address.
            </li>
            <li>
              <strong>Xbox Teredo Network Conflicts:</strong> Xbox consoles use the Teredo tunneling protocol to establish peer-to-peer connections. If the router&apos;s DHCP server assigns incorrect default DNS settings, or if UPnP is disabled, Teredo cannot resolve routing targets. Configure a static IP on the Xbox and set the primary DNS to Cloudflare (<code className="font-mono">1.1.1.1</code>) or Google (<code className="font-mono">8.8.8.8</code>) to resolve this.
            </li>
          </ul>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Brand-Specific DHCP Settings Navigation</h2>
          <p>
            If you need to adjust DHCP parameters, lease durations, or configure static IP reservations, use the paths below to locate the settings in your router&apos;s admin panel:
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)] uppercase">1. TP-Link (Archer series)</h3>
          <p>
            Go to **Advanced** &rarr; **Network** &rarr; **DHCP Server**. 
            Here, you can modify the Start and End IP address pool ranges, adjust the lease time (we recommend 1440 minutes / 24 hours), and configure DNS addresses.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)] uppercase">2. ASUS (ASUSWRT console)</h3>
          <p>
            Go to **Advanced Settings** &rarr; **LAN** &rarr; **DHCP Server** tab. 
            Enable the DHCP Server toggle. You can set the IP pool range and configure **Manual Assignment** (MAC binding) at the bottom of the page.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)] uppercase">3. Netgear (Nighthawk / Orbi)</h3>
          <p>
            Go to **Advanced** &rarr; **Setup** &rarr; **LAN Setup**. 
            Ensure the **Use Router as DHCP Server** checkbox is selected. You can set the start and end IP addresses and configure static address reservations here.
          </p>

          <h3 className="text-xs font-bold text-[var(--text-primary)] uppercase">4. Linksys</h3>
          <p>
            Go to **Connectivity** &rarr; **Local Network** &rarr; **DHCP Server**. 
            Toggle the DHCP Server to Enabled, adjust the client lease time, and save your changes.
          </p>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">Hardware Failures Causing DHCP Drops</h2>
          <p>
            If a router continues to drop DHCP allocations even after a factory reset and with minimal devices connected, the hardware itself may be failing:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>RAM Degradation:</strong> The DHCP lease table is maintained in the router&apos;s system RAM. If the RAM chips degrade due to voltage fluctuations or age, data writes to the lease tables can fail, causing the DHCP service to crash.
            </li>
            <li>
              <strong>Thermal Throttling of the Switch SoC:</strong> Many home routers are fanless and rely on small passive heatsinks. If the router is placed in an unventilated area, the switch chip can overheat. This causes the router to drop packets and fail to process DHCP broadcasts, even while maintaining active LED link lights.
            </li>
            <li>
              <strong>Physical Port and PHY Chip Faults:</strong> Power surges can damage the physical Ethernet PHY transceiver chips behind the LAN ports. This damage can prevent client handshake frames from reaching the CPU, preventing the DHCP server from receiving the Discover request.
            </li>
            <li>
              <strong>Capacitor Aging:</strong> Swollen or failing electrolytic capacitors on the router&apos;s mainboard can cause voltage instability, leading to random CPU resets and crashes of network daemons like the DHCP service.
            </li>
          </ul>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">How ISPs Detect DHCP Issues Remotely</h2>
          <p>
            Internet Service Providers monitor network equipment performance up to your home gateway using several telemetry tools:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>CMTS Loop Diagnostic Logging:</strong> On cable networks, the **Cable Modem Termination System (CMTS)** monitors downstream DOCSIS channels. If a client router generates broadcast storms (e.g., from an STP network loop), the CMTS logs an alert and may throttle the connection to protect the node.
            </li>
            <li>
              <strong>DHCP IP Lease Expiry Telemetry:</strong> ISP routers check RADIUS and DHCP server logs for lease request patterns. If your router stops sending DHCP Request packets before its WAN lease expires, the ISP systems will log a provisioning timeout and mark the connection as offline.
            </li>
            <li>
              <strong>Modem SNMP Poll Errors:</strong> ISPs use Simple Network Management Protocol (SNMP) to poll modems and ONT units. If the ONT reports high packet drop rates on its Ethernet port, it indicates a link negotiation issue between the modem and your primary router.
            </li>
          </ul>

          <h2 className="text-sm font-bold text-[var(--text-primary)]">When to Replace Your Router</h2>
          <p>
            Troubleshooting can only resolve configuration errors. If your router displays the following symptoms, it is time to replace the hardware:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-[11px] text-[var(--text-muted)]">
            <li>
              <strong>Recurring DHCP Crashes:</strong> The router stops assigning IP addresses every 24 to 48 hours, requiring a physical power cycle to restore network connectivity.
            </li>
            <li>
              <strong>NVRAM Write Errors:</strong> Settings changes, static IP reservations, or custom DNS configurations revert to default values after the router is rebooted.
            </li>
            <li>
              <strong>High Thermal Output:</strong> The router chassis feels hot to the touch, and throughput speeds drop under heavy network load.
            </li>
          </ul>
        </article>
      </div>
    </TroubleshootingArticleShell>
  );
}
